name: Deploy Laravel to FTP

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, bcmath, curl

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Prepare Laravel App
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Prepare deployment folder (exclude node_modules and others)
        run: |
          rm -rf deploy
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='.github' --exclude='tests' --exclude='README.md' --exclude='.env' ./ deploy/

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: ./deploy
          server-dir: ${{ secrets.FTP_TARGET }}
          clean: true
          exclude: |
            .git*
            .github*
            node_modules*
            tests*
            README.md
            .env
